trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
    - npm  

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.100'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm -g azurite'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'Install Azurite'
  command: 'install -g azurite'
  inputs:
    verbose: false    

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'